// src/components/TabBar.vue
<template>
  <nav class="fixed bottom-0 left-0 right-0 h-14 bg-surface border-t border-text-muted/10 flex items-center justify-around pb-safe z-50">
    <router-link
      v-for="item in items"
      :key="item.path"
      :to="item.path"
      class="flex flex-col items-center justify-center gap-0.5 w-16 text-text-muted transition-colors"
      :class="{ 'text-primary': route.path === item.path }"
    >
      <component :is="item.icon" class="w-6 h-6" />
      <span class="text-[10px] font-medium">{{ item.label }}</span>
    </router-link>
  </nav>
</template>

<script setup lang="ts">
import { useRoute } from 'vue-router'
import { HomeIcon, ChartBarIcon, DocumentTextIcon, UserIcon } from '@heroicons/vue/24/outline'

const route = useRoute()

const items = [
  { path: '/', label: '练习', icon: HomeIcon },
  { path: '/stats', label: '统计', icon: ChartBarIcon },
  { path: '/char-sets', label: '字集', icon: DocumentTextIcon },
  { path: '/profile', label: '我的', icon: UserIcon }
]
</script>

// src/components/TabBar.tsx
interface TabBarProps {
  tab: "practice" | "stats" | "charsets" | "profile";
  onChange: (t: "practice" | "stats" | "charsets" | "profile") => void;
}

const tabs = [
  { id: "practice", label: "练习", icon: "✎" },
  { id: "stats", label: "统计", icon: "▤" },
  { id: "charsets", label: "字集", icon: "字" },
  { id: "profile", label: "我的", icon: "◉" },
] as const;

export function TabBar({ tab, onChange }: TabBarProps) {
  return (
    <nav className="flex border-t border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 safe-bottom safe-x">
      {tabs.map((t) => (
        <button
          key={t.id}
          onClick={() => onChange(t.id)}
          className={`flex-1 flex flex-col items-center justify-center py-2.5 gap-0.5 transition-colors ${
            tab === t.id
              ? "text-accent"
              : "text-zinc-400 dark:text-zinc-500"
          }`}
        >
          <span className="text-xl leading-none">{t.icon}</span>
          <span className="text-[11px]">{t.label}</span>
        </button>
      ))}
    </nav>
  );
}
